---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace: daas
spec:
  clusterIP: None
  ports:
  - port: 9042
    protocol: TCP
    targetPort: 9042
  publishNotReadyAddresses: true
  selector:
    app: cassandra
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
